baseURL = "http://anmolrattansingh.github.io"
title = "Anmol Sandhu"
publishDir = "public"


languageCode = "en-us"
copyright = ""

[author]
    name = "Anmol Sandhu"

[params]
    dateFormat = "Jan 2, 2006"
    description = "Anmol Sandhu's personal website."
    # images = ["/img/cover.png"]

# See https://feathericons.com/
# The value of pre is the icon name
[menux]
  [[menu.main]]
    name = "All Projects"
    pre = "archive"
    url = "/projects"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags"
    weight = 1
  [[menu.main]]
    name = "Contact"
    pre = "at-sign"
    url = "/about"
    weight = 2

[footer]
  [[footer.main]]
    name = " "
    pre = "github"
    url = "https://github.com/AnmolRattanSingh"
    weight = 1
  [[footer.main]]
    name = ""
    re = "linkedin"
    url = "https://www.linkedin.com/in/anmolrattansinghsandhu/"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"

[imaging]
bgColor = "#777777"
